name: test download and sign
on:
  workflow_dispatch:
    inputs:
      DEBUG_MODE:
        description: DEBUG_MODE
        default: 'no'
env:
  ANDROID_SIGNING_KEY: '${{ secrets.ANDROID_SIGNING_KEY }}'
  
jobs:
  test_download:
    name: test_download-${{ matrix.job.cfg }}
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { cfg: apk, os: windows-latest }
    steps:
      - name: checkout
        uses: deep-soft/checkout@v4

      - name: test download
        shell: bash
        run: |
          name_common=$(cat bin/bin-common.txt);
          name_apk=$(cat bin/bin-${{ matrix.job.cfg }}.txt);
          echo $name_common;
          echo $name_apk;
          #curl refs/tags/bins/$name_apk -o $name_apk;
          mkdir tmp
          pushd tmp
          echo "curl -LOJ $name_common$name_apk;"
          curl -LOJ $name_common$name_apk;
          # name_apk_full=$(find . -type f -name $name_apk -print0 | xargs -0 realpath)
          name_apk_full=$(find . -name "$name_apk" | xargs readlink -f)
          echo "name_apk_full=$name_apk_full" >> $GITHUB_ENV
          echo "list: pushd"
          ls -l
          popd
          echo "list: popd"
          ls -l
      
      - name: test archive
        shell: bash
        run: |
          pushd tmp
          echo "name_apk_full: ${{ env.name_apk_full }}"
          file "${{ env.name_apk_full }}"
          xz -vt "${{ env.name_apk_full }}"
          # if [ "${{ matrix.job.cfg }}" == "win" ]; then
          #   xz -9 ${{ env.name_apk_full }}
          #   name_xz_full=$(find . -name "*.xz" | xargs readlink -f)
          #   ls -l $name_xz_full
          #   echo "name_xz_full=$name_xz_full" >> $GITHUB_ENV            
          # else
          #   xz -vt "${{ env.name_apk_full }}"
          # fi
          popd

      - name: unpack archive
        shell: bash
        run: |
          pushd tmp
          echo "name_apk_full: ${{ env.name_apk_full }}"
          file "${{ env.name_apk_full }}"
          xz -d "${{ env.name_apk_full }}"
          ls -la ./
          popd

      - uses: deep-soft/sign-android-release@v2
        name: Sign app APK
        if: env.ANDROID_SIGNING_KEY != null
        id: sign-android-apk
        with:
          releaseDirectory: ./tmp
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
        env:
          # override default build-tools version (29.0.3) -- optional
          BUILD_TOOLS_VERSION: "34.0.0"

      - uses: deep-soft/zip-release@v2
        with:
          type: zip
          filename: 'test-1'
          directory: 'tmp'
          path: '*.apk'
          env_variable: 'zip_1'
          #inclusions: 'a'
          #exclusions: 'someotherfile*'
          verbose: ${{ inputs.DEBUG_MODE }}
          debug: ${{ inputs.DEBUG_MODE }}

      - name: Publish archives
        continue-on-error: true
        uses: deep-soft/action-gh-release@v2.1
        with:
          fail_on_unmatched_files: false
          draft: true
          tag_name: test_archives
          files: |
            ${{ env.zip_1 }}
            ${{ env.SIGNED_RELEASE_FILE }}
            ./tmp/*.apk

#      - name: Upload Artifact
#        if: ${{ matrix.job.cfg == 'win' }}
#        uses: deep-soft/upload-artifact@v4
#        with:
#          name: xz
#          path: |
#            ${{ env.name_xz_full }}
#            tmp
